export const IS_OPEN_SIDEBAR_CART = 'IS_OPEN_SIDEBAR_CART';
export const IS_OPEN_SIDEBAR_CATEGORY = 'IS_OPEN_SIDEBAR_CATEGORY';
export const IS_OPEN_SIDEBAR_NOTIFICATION = 'IS_OPEN_SIDEBAR_NOTIFICATION';
export const IS_OPEN_SIDEBAR = 'IS_OPEN_SIDEBAR';
