export const FETCH_CATEGORY_LOADING = 'FETCH_CATEGORY_LOADING';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';
export const CLEANUP_CATEGORY_DATA = 'CLEANUP_CATEGORY_DATA';

export const FETCH_PRODUCTS_LOADING = 'FETCH_PRODUCTS_LOADING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const CLEANUP_PRODUCTS_DATA = 'CLEANUP_PRODUCTS_DATA';

export const FETCH_SPECIFIC_CATEGORY_LOADING = 'FETCH_SPECIFIC_CATEGORY_LOADING';
export const FETCH_SPECIFIC_CATEGORY_SUCCESS = 'FETCH_SPECIFIC_CATEGORY_SUCCESS';
export const FETCH_SPECIFIC_CATEGORY_ERROR = 'FETCH_SPECIFIC_CATEGORY_ERROR';
export const CLEANUP_SPECIFIC_CATEGORY_DATA = 'CLEANUP_SPECIFIC_CATEGORY_DATA';

export const FETCH_SPECIFIC_PRODUCTS_LOADING = 'FETCH_SPECIFIC_PRODUCTS_LOADING';
export const FETCH_SPECIFIC_PRODUCTS_SUCCESS = 'FETCH_SPECIFIC_PRODUCTS_SUCCESS';
export const FETCH_SPECIFIC_PRODUCTS_ERROR = 'FETCH_SPECIFIC_PRODUCTS_ERROR';
export const CLEANUP_SPECIFIC_PRODUCTS_DATA = 'CLEANUP_SPECIFIC_PRODUCTS_DATA';
